#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedLoginSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBLoginSystem")]
	public sealed partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRole(Role instance);
    partial void UpdateRole(Role instance);
    partial void DeleteRole(Role instance);
    partial void Insertcustomer(customer instance);
    partial void Updatecustomer(customer instance);
    partial void Deletecustomer(customer instance);
    partial void Insertcust_vehicle(cust_vehicle instance);
    partial void Updatecust_vehicle(cust_vehicle instance);
    partial void Deletecust_vehicle(cust_vehicle instance);
    partial void InsertEmpPinTable(EmpPinTable instance);
    partial void UpdateEmpPinTable(EmpPinTable instance);
    partial void DeleteEmpPinTable(EmpPinTable instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::AdvancedLoginSystem.Properties.Settings.Default.DBLoginSystem, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Role> Roles
		{
			get
			{
				return this.GetTable<Role>();
			}
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<cust_vehicle> cust_vehicles
		{
			get
			{
				return this.GetTable<cust_vehicle>();
			}
		}
		
		public System.Data.Linq.Table<EmpPinTable> EmpPinTables
		{
			get
			{
				return this.GetTable<EmpPinTable>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spSearchViewUsers")]
		public ISingleResult<spSearchViewUsersResult> spSearchViewUsers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="VarChar(50)")] string search)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), search);
			return ((ISingleResult<spSearchViewUsersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spChangePassword")]
		public int spChangePassword([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrentPassword", DbType="VarChar(50)")] string currentPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewPassword", DbType="VarChar(50)")] string newPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConfNewPassword", DbType="VarChar(50)")] string confNewPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="VarChar(MAX)")] ref string result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, currentPassword, newPassword, confNewPassword, result);
			result = ((string)(result1.GetParameterValue(4)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAuthentication")]
		public int spAuthentication([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="VarChar(100)")] ref string result, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Role", DbType="VarChar(50)")] ref string role, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string userName)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password, result, role, userName);
			result = ((string)(result1.GetParameterValue(2)));
			role = ((string)(result1.GetParameterValue(3)));
			userName = ((string)(result1.GetParameterValue(4)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spReadUsers")]
		public int spReadUsers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_no, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] ref string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] ref string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Role", DbType="VarChar(50)")] ref string role, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActivated", DbType="VarChar(50)")] ref string isActivated)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emp_no, userName, email, role, isActivated);
			userName = ((string)(result.GetParameterValue(1)));
			email = ((string)(result.GetParameterValue(2)));
			role = ((string)(result.GetParameterValue(3)));
			isActivated = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRegister")]
		public int spRegister([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="Int")] System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="VarChar(50)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Answer", DbType="VarChar(50)")] string answer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpPinNo", DbType="Int")] System.Nullable<int> empPinNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="VarChar(MAX)")] ref string result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, password, email, roleID, question, answer, empPinNo, result);
			result = ((string)(result1.GetParameterValue(7)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spManageUsers")]
		public int spManageUsers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> emp_no, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Role", DbType="Int")] System.Nullable<int> role, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="VarChar(MAX)")] ref string result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emp_no, role, isActive, result);
			result = ((string)(result1.GetParameterValue(3)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCheckEmail")]
		public int spCheckEmail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Action", DbType="VarChar(50)")] string action, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="VarChar(50)")] ref string result, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionOut", DbType="VarChar(50)")] ref string questionOut, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnswerIn", DbType="VarChar(50)")] string answerIn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChangePassword", DbType="VarChar(50)")] string changePassword)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, action, result, questionOut, answerIn, changePassword);
			result = ((string)(result1.GetParameterValue(2)));
			questionOut = ((string)(result1.GetParameterValue(3)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PinAuthProcedure")]
		public ISingleResult<PinAuthProcedureResult> PinAuthProcedure([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpPin", DbType="Int")] System.Nullable<int> empPin, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpNo", DbType="Int")] System.Nullable<int> empNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PinResult", DbType="VarChar(100)")] ref string pinResult)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, empPin, empNo, pinResult);
			pinResult = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<PinAuthProcedureResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spRegister")]
		public int spRegister1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="Int")] System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="VarChar(50)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Answer", DbType="VarChar(50)")] string answer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TextPinIn", DbType="VarChar(50)")] string textPinIn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="VarChar(MAX)")] ref string result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, password, email, roleID, question, answer, textPinIn, firstName, lastName, result);
			result = ((string)(result1.GetParameterValue(9)));
			return ((int)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spFastLogin")]
		public ISingleResult<spFastLoginResult> spFastLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TextPinIn", DbType="VarChar(50)")] string textPinIn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Role", DbType="VarChar(50)")] ref string role, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] ref string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="VarChar(100)")] ref string result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), textPinIn, email, role, userName, result);
			role = ((string)(result1.GetParameterValue(2)));
			userName = ((string)(result1.GetParameterValue(3)));
			result = ((string)(result1.GetParameterValue(4)));
			return ((ISingleResult<spFastLoginResult>)(result1.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spAddCust")]
		public int spAddCust([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_firstname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_lastname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string buiss_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_landline, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_fir_line_add, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_sec_line_add, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_city, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_county, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string cust_postcode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string cust_invoice_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NText")] string cust_add_notes, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] ref string result)
		{
			IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cust_firstname, cust_lastname, buiss_name, cust_landline, cust_mobile, cust_fir_line_add, cust_sec_line_add, cust_city, cust_county, cust_postcode, cust_email, cust_invoice_id, cust_add_notes, result);
			result = ((string)(result1.GetParameterValue(13)));
			return ((int)(result1.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Roles")]
	public partial class Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private string _RoleName;
		
		private EntitySet<User> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    #endregion
		
		public Role()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this.OnRoleNameChanging(value);
					this.SendPropertyChanging();
					this._RoleName = value;
					this.SendPropertyChanged("RoleName");
					this.OnRoleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Role_User", Storage="_Users", ThisKey="RoleID", OtherKey="RoleID")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Role = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Role = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customers")]
	public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _customer_Id;
		
		private string _cust_firstname;
		
		private string _cust_lastname;
		
		private string _buiss_name;
		
		private System.Nullable<long> _cust_landline;
		
		private System.Nullable<long> _cust_mobile;
		
		private string _cust_fir_line_add;
		
		private string _cust_sec_line_add;
		
		private string _cust_city;
		
		private string _cust_county;
		
		private string _cust_postcode;
		
		private string _cust_email;
		
		private System.Nullable<long> _cust_invoice_id;
		
		private string _cust_add_notes;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<long> _emp_no;
		
		private EntitySet<cust_vehicle> _cust_vehicles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncustomer_IdChanging(long value);
    partial void Oncustomer_IdChanged();
    partial void Oncust_firstnameChanging(string value);
    partial void Oncust_firstnameChanged();
    partial void Oncust_lastnameChanging(string value);
    partial void Oncust_lastnameChanged();
    partial void Onbuiss_nameChanging(string value);
    partial void Onbuiss_nameChanged();
    partial void Oncust_landlineChanging(System.Nullable<long> value);
    partial void Oncust_landlineChanged();
    partial void Oncust_mobileChanging(System.Nullable<long> value);
    partial void Oncust_mobileChanged();
    partial void Oncust_fir_line_addChanging(string value);
    partial void Oncust_fir_line_addChanged();
    partial void Oncust_sec_line_addChanging(string value);
    partial void Oncust_sec_line_addChanged();
    partial void Oncust_cityChanging(string value);
    partial void Oncust_cityChanged();
    partial void Oncust_countyChanging(string value);
    partial void Oncust_countyChanged();
    partial void Oncust_postcodeChanging(string value);
    partial void Oncust_postcodeChanged();
    partial void Oncust_emailChanging(string value);
    partial void Oncust_emailChanged();
    partial void Oncust_invoice_idChanging(System.Nullable<long> value);
    partial void Oncust_invoice_idChanged();
    partial void Oncust_add_notesChanging(string value);
    partial void Oncust_add_notesChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void Onemp_noChanging(System.Nullable<long> value);
    partial void Onemp_noChanged();
    #endregion
		
		public customer()
		{
			this._cust_vehicles = new EntitySet<cust_vehicle>(new Action<cust_vehicle>(this.attach_cust_vehicles), new Action<cust_vehicle>(this.detach_cust_vehicles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long customer_Id
		{
			get
			{
				return this._customer_Id;
			}
			set
			{
				if ((this._customer_Id != value))
				{
					this.Oncustomer_IdChanging(value);
					this.SendPropertyChanging();
					this._customer_Id = value;
					this.SendPropertyChanged("customer_Id");
					this.Oncustomer_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_firstname", DbType="Char(15)")]
		public string cust_firstname
		{
			get
			{
				return this._cust_firstname;
			}
			set
			{
				if ((this._cust_firstname != value))
				{
					this.Oncust_firstnameChanging(value);
					this.SendPropertyChanging();
					this._cust_firstname = value;
					this.SendPropertyChanged("cust_firstname");
					this.Oncust_firstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_lastname", DbType="Char(15)")]
		public string cust_lastname
		{
			get
			{
				return this._cust_lastname;
			}
			set
			{
				if ((this._cust_lastname != value))
				{
					this.Oncust_lastnameChanging(value);
					this.SendPropertyChanging();
					this._cust_lastname = value;
					this.SendPropertyChanged("cust_lastname");
					this.Oncust_lastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buiss_name", DbType="Char(50)")]
		public string buiss_name
		{
			get
			{
				return this._buiss_name;
			}
			set
			{
				if ((this._buiss_name != value))
				{
					this.Onbuiss_nameChanging(value);
					this.SendPropertyChanging();
					this._buiss_name = value;
					this.SendPropertyChanged("buiss_name");
					this.Onbuiss_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_landline", DbType="BigInt")]
		public System.Nullable<long> cust_landline
		{
			get
			{
				return this._cust_landline;
			}
			set
			{
				if ((this._cust_landline != value))
				{
					this.Oncust_landlineChanging(value);
					this.SendPropertyChanging();
					this._cust_landline = value;
					this.SendPropertyChanged("cust_landline");
					this.Oncust_landlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_mobile", DbType="BigInt")]
		public System.Nullable<long> cust_mobile
		{
			get
			{
				return this._cust_mobile;
			}
			set
			{
				if ((this._cust_mobile != value))
				{
					this.Oncust_mobileChanging(value);
					this.SendPropertyChanging();
					this._cust_mobile = value;
					this.SendPropertyChanged("cust_mobile");
					this.Oncust_mobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_fir_line_add", DbType="Char(10)")]
		public string cust_fir_line_add
		{
			get
			{
				return this._cust_fir_line_add;
			}
			set
			{
				if ((this._cust_fir_line_add != value))
				{
					this.Oncust_fir_line_addChanging(value);
					this.SendPropertyChanging();
					this._cust_fir_line_add = value;
					this.SendPropertyChanged("cust_fir_line_add");
					this.Oncust_fir_line_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_sec_line_add", DbType="Char(10)")]
		public string cust_sec_line_add
		{
			get
			{
				return this._cust_sec_line_add;
			}
			set
			{
				if ((this._cust_sec_line_add != value))
				{
					this.Oncust_sec_line_addChanging(value);
					this.SendPropertyChanging();
					this._cust_sec_line_add = value;
					this.SendPropertyChanged("cust_sec_line_add");
					this.Oncust_sec_line_addChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_city", DbType="Char(20)")]
		public string cust_city
		{
			get
			{
				return this._cust_city;
			}
			set
			{
				if ((this._cust_city != value))
				{
					this.Oncust_cityChanging(value);
					this.SendPropertyChanging();
					this._cust_city = value;
					this.SendPropertyChanged("cust_city");
					this.Oncust_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_county", DbType="Char(20)")]
		public string cust_county
		{
			get
			{
				return this._cust_county;
			}
			set
			{
				if ((this._cust_county != value))
				{
					this.Oncust_countyChanging(value);
					this.SendPropertyChanging();
					this._cust_county = value;
					this.SendPropertyChanged("cust_county");
					this.Oncust_countyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_postcode", DbType="Char(10)")]
		public string cust_postcode
		{
			get
			{
				return this._cust_postcode;
			}
			set
			{
				if ((this._cust_postcode != value))
				{
					this.Oncust_postcodeChanging(value);
					this.SendPropertyChanging();
					this._cust_postcode = value;
					this.SendPropertyChanged("cust_postcode");
					this.Oncust_postcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_email", DbType="Char(20)")]
		public string cust_email
		{
			get
			{
				return this._cust_email;
			}
			set
			{
				if ((this._cust_email != value))
				{
					this.Oncust_emailChanging(value);
					this.SendPropertyChanging();
					this._cust_email = value;
					this.SendPropertyChanged("cust_email");
					this.Oncust_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_invoice_id", DbType="BigInt")]
		public System.Nullable<long> cust_invoice_id
		{
			get
			{
				return this._cust_invoice_id;
			}
			set
			{
				if ((this._cust_invoice_id != value))
				{
					this.Oncust_invoice_idChanging(value);
					this.SendPropertyChanging();
					this._cust_invoice_id = value;
					this.SendPropertyChanged("cust_invoice_id");
					this.Oncust_invoice_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_add_notes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string cust_add_notes
		{
			get
			{
				return this._cust_add_notes;
			}
			set
			{
				if ((this._cust_add_notes != value))
				{
					this.Oncust_add_notesChanging(value);
					this.SendPropertyChanging();
					this._cust_add_notes = value;
					this.SendPropertyChanged("cust_add_notes");
					this.Oncust_add_notesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_no", DbType="BigInt")]
		public System.Nullable<long> emp_no
		{
			get
			{
				return this._emp_no;
			}
			set
			{
				if ((this._emp_no != value))
				{
					this.Onemp_noChanging(value);
					this.SendPropertyChanging();
					this._emp_no = value;
					this.SendPropertyChanged("emp_no");
					this.Onemp_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_cust_vehicle", Storage="_cust_vehicles", ThisKey="customer_Id", OtherKey="customer_Id")]
		public EntitySet<cust_vehicle> cust_vehicles
		{
			get
			{
				return this._cust_vehicles;
			}
			set
			{
				this._cust_vehicles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cust_vehicles(cust_vehicle entity)
		{
			this.SendPropertyChanging();
			entity.customer = this;
		}
		
		private void detach_cust_vehicles(cust_vehicle entity)
		{
			this.SendPropertyChanging();
			entity.customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cust_vehicle")]
	public partial class cust_vehicle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<long> _customer_Id;
		
		private string _vehicle_reg;
		
		private string _cust_vin_no;
		
		private string _vehicle_make;
		
		private System.Nullable<int> _year_of_make;
		
		private string _vehicle_colour;
		
		private string _colour_code;
		
		private string _cust_veh_notes;
		
		private EntityRef<customer> _customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncustomer_IdChanging(System.Nullable<long> value);
    partial void Oncustomer_IdChanged();
    partial void Onvehicle_regChanging(string value);
    partial void Onvehicle_regChanged();
    partial void Oncust_vin_noChanging(string value);
    partial void Oncust_vin_noChanged();
    partial void Onvehicle_makeChanging(string value);
    partial void Onvehicle_makeChanged();
    partial void Onyear_of_makeChanging(System.Nullable<int> value);
    partial void Onyear_of_makeChanged();
    partial void Onvehicle_colourChanging(string value);
    partial void Onvehicle_colourChanged();
    partial void Oncolour_codeChanging(string value);
    partial void Oncolour_codeChanged();
    partial void Oncust_veh_notesChanging(string value);
    partial void Oncust_veh_notesChanged();
    #endregion
		
		public cust_vehicle()
		{
			this._customer = default(EntityRef<customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_Id", DbType="BigInt")]
		public System.Nullable<long> customer_Id
		{
			get
			{
				return this._customer_Id;
			}
			set
			{
				if ((this._customer_Id != value))
				{
					if (this._customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncustomer_IdChanging(value);
					this.SendPropertyChanging();
					this._customer_Id = value;
					this.SendPropertyChanged("customer_Id");
					this.Oncustomer_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle_reg", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vehicle_reg
		{
			get
			{
				return this._vehicle_reg;
			}
			set
			{
				if ((this._vehicle_reg != value))
				{
					this.Onvehicle_regChanging(value);
					this.SendPropertyChanging();
					this._vehicle_reg = value;
					this.SendPropertyChanged("vehicle_reg");
					this.Onvehicle_regChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_vin_no", DbType="NChar(30)")]
		public string cust_vin_no
		{
			get
			{
				return this._cust_vin_no;
			}
			set
			{
				if ((this._cust_vin_no != value))
				{
					this.Oncust_vin_noChanging(value);
					this.SendPropertyChanging();
					this._cust_vin_no = value;
					this.SendPropertyChanged("cust_vin_no");
					this.Oncust_vin_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle_make", DbType="NChar(20)")]
		public string vehicle_make
		{
			get
			{
				return this._vehicle_make;
			}
			set
			{
				if ((this._vehicle_make != value))
				{
					this.Onvehicle_makeChanging(value);
					this.SendPropertyChanging();
					this._vehicle_make = value;
					this.SendPropertyChanged("vehicle_make");
					this.Onvehicle_makeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_of_make", DbType="Int")]
		public System.Nullable<int> year_of_make
		{
			get
			{
				return this._year_of_make;
			}
			set
			{
				if ((this._year_of_make != value))
				{
					this.Onyear_of_makeChanging(value);
					this.SendPropertyChanging();
					this._year_of_make = value;
					this.SendPropertyChanged("year_of_make");
					this.Onyear_of_makeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vehicle_colour", DbType="NChar(20)")]
		public string vehicle_colour
		{
			get
			{
				return this._vehicle_colour;
			}
			set
			{
				if ((this._vehicle_colour != value))
				{
					this.Onvehicle_colourChanging(value);
					this.SendPropertyChanging();
					this._vehicle_colour = value;
					this.SendPropertyChanged("vehicle_colour");
					this.Onvehicle_colourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colour_code", DbType="NChar(20)")]
		public string colour_code
		{
			get
			{
				return this._colour_code;
			}
			set
			{
				if ((this._colour_code != value))
				{
					this.Oncolour_codeChanging(value);
					this.SendPropertyChanging();
					this._colour_code = value;
					this.SendPropertyChanged("colour_code");
					this.Oncolour_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_veh_notes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string cust_veh_notes
		{
			get
			{
				return this._cust_veh_notes;
			}
			set
			{
				if ((this._cust_veh_notes != value))
				{
					this.Oncust_veh_notesChanging(value);
					this.SendPropertyChanging();
					this._cust_veh_notes = value;
					this.SendPropertyChanged("cust_veh_notes");
					this.Oncust_veh_notesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_cust_vehicle", Storage="_customer", ThisKey="customer_Id", OtherKey="customer_Id", IsForeignKey=true, DeleteRule="CASCADE")]
		public customer customer
		{
			get
			{
				return this._customer.Entity;
			}
			set
			{
				customer previousValue = this._customer.Entity;
				if (((previousValue != value) 
							|| (this._customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._customer.Entity = null;
						previousValue.cust_vehicles.Remove(this);
					}
					this._customer.Entity = value;
					if ((value != null))
					{
						value.cust_vehicles.Add(this);
						this._customer_Id = value.customer_Id;
					}
					else
					{
						this._customer_Id = default(Nullable<long>);
					}
					this.SendPropertyChanged("customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmpPinTable")]
	public partial class EmpPinTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _emp_no;
		
		private System.Nullable<int> _emp_pin;
		
		private string _FirstName;
		
		private string _LastName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_noChanging(int value);
    partial void Onemp_noChanged();
    partial void Onemp_pinChanging(System.Nullable<int> value);
    partial void Onemp_pinChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    #endregion
		
		public EmpPinTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int emp_no
		{
			get
			{
				return this._emp_no;
			}
			set
			{
				if ((this._emp_no != value))
				{
					this.Onemp_noChanging(value);
					this.SendPropertyChanging();
					this._emp_no = value;
					this.SendPropertyChanged("emp_no");
					this.Onemp_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_pin", DbType="Int")]
		public System.Nullable<int> emp_pin
		{
			get
			{
				return this._emp_pin;
			}
			set
			{
				if ((this._emp_pin != value))
				{
					this.Onemp_pinChanging(value);
					this.SendPropertyChanging();
					this._emp_pin = value;
					this.SendPropertyChanged("emp_pin");
					this.Onemp_pinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _emp_no;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Email;
		
		private System.Nullable<int> _RetryAttempts;
		
		private System.Nullable<bool> _IsActivated;
		
		private System.Nullable<bool> _IsLocked;
		
		private System.Nullable<System.DateTime> _DeactivatedDateTime;
		
		private System.Nullable<System.DateTime> _LockedDateTime;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _LastLogin;
		
		private int _RoleID;
		
		private string _SecretQuestion;
		
		private string _SecretAnswer;
		
		private string _emp_pin;
		
		private string _FirstName;
		
		private string _LastName;
		
		private EntityRef<Role> _Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_noChanging(int value);
    partial void Onemp_noChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnRetryAttemptsChanging(System.Nullable<int> value);
    partial void OnRetryAttemptsChanged();
    partial void OnIsActivatedChanging(System.Nullable<bool> value);
    partial void OnIsActivatedChanged();
    partial void OnIsLockedChanging(System.Nullable<bool> value);
    partial void OnIsLockedChanged();
    partial void OnDeactivatedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDeactivatedDateTimeChanged();
    partial void OnLockedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLockedDateTimeChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnLastLoginChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoginChanged();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnSecretQuestionChanging(string value);
    partial void OnSecretQuestionChanged();
    partial void OnSecretAnswerChanging(string value);
    partial void OnSecretAnswerChanged();
    partial void Onemp_pinChanging(string value);
    partial void Onemp_pinChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    #endregion
		
		public User()
		{
			this._Role = default(EntityRef<Role>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int emp_no
		{
			get
			{
				return this._emp_no;
			}
			set
			{
				if ((this._emp_no != value))
				{
					this.Onemp_noChanging(value);
					this.SendPropertyChanging();
					this._emp_no = value;
					this.SendPropertyChanged("emp_no");
					this.Onemp_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetryAttempts", DbType="Int")]
		public System.Nullable<int> RetryAttempts
		{
			get
			{
				return this._RetryAttempts;
			}
			set
			{
				if ((this._RetryAttempts != value))
				{
					this.OnRetryAttemptsChanging(value);
					this.SendPropertyChanging();
					this._RetryAttempts = value;
					this.SendPropertyChanged("RetryAttempts");
					this.OnRetryAttemptsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActivated", DbType="Bit")]
		public System.Nullable<bool> IsActivated
		{
			get
			{
				return this._IsActivated;
			}
			set
			{
				if ((this._IsActivated != value))
				{
					this.OnIsActivatedChanging(value);
					this.SendPropertyChanging();
					this._IsActivated = value;
					this.SendPropertyChanged("IsActivated");
					this.OnIsActivatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit")]
		public System.Nullable<bool> IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeactivatedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeactivatedDateTime
		{
			get
			{
				return this._DeactivatedDateTime;
			}
			set
			{
				if ((this._DeactivatedDateTime != value))
				{
					this.OnDeactivatedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DeactivatedDateTime = value;
					this.SendPropertyChanged("DeactivatedDateTime");
					this.OnDeactivatedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LockedDateTime
		{
			get
			{
				return this._LockedDateTime;
			}
			set
			{
				if ((this._LockedDateTime != value))
				{
					this.OnLockedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._LockedDateTime = value;
					this.SendPropertyChanged("LockedDateTime");
					this.OnLockedDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this.OnLastLoginChanging(value);
					this.SendPropertyChanging();
					this._LastLogin = value;
					this.SendPropertyChanged("LastLogin");
					this.OnLastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					if (this._Role.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecretQuestion", DbType="VarChar(50)")]
		public string SecretQuestion
		{
			get
			{
				return this._SecretQuestion;
			}
			set
			{
				if ((this._SecretQuestion != value))
				{
					this.OnSecretQuestionChanging(value);
					this.SendPropertyChanging();
					this._SecretQuestion = value;
					this.SendPropertyChanged("SecretQuestion");
					this.OnSecretQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecretAnswer", DbType="NChar(10)")]
		public string SecretAnswer
		{
			get
			{
				return this._SecretAnswer;
			}
			set
			{
				if ((this._SecretAnswer != value))
				{
					this.OnSecretAnswerChanging(value);
					this.SendPropertyChanging();
					this._SecretAnswer = value;
					this.SendPropertyChanged("SecretAnswer");
					this.OnSecretAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_pin", DbType="VarChar(50)")]
		public string emp_pin
		{
			get
			{
				return this._emp_pin;
			}
			set
			{
				if ((this._emp_pin != value))
				{
					this.Onemp_pinChanging(value);
					this.SendPropertyChanging();
					this._emp_pin = value;
					this.SendPropertyChanged("emp_pin");
					this.Onemp_pinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Role_User", Storage="_Role", ThisKey="RoleID", OtherKey="RoleID", IsForeignKey=true)]
		public Role Role
		{
			get
			{
				return this._Role.Entity;
			}
			set
			{
				Role previousValue = this._Role.Entity;
				if (((previousValue != value) 
							|| (this._Role.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Role.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._Role.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._RoleID = value.RoleID;
					}
					else
					{
						this._RoleID = default(int);
					}
					this.SendPropertyChanged("Role");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spSearchViewUsersResult
	{
		
		private int _emp_no;
		
		private string _UserName;
		
		private string _Email;
		
		private System.Nullable<int> _RetryAttempts;
		
		private System.Nullable<bool> _IsActivated;
		
		private System.Nullable<bool> _IsLocked;
		
		private System.Nullable<System.DateTime> _DeactivatedDateTime;
		
		private System.Nullable<System.DateTime> _LockedDateTime;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _LastLogin;
		
		private string _RoleName;
		
		public spSearchViewUsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_no", DbType="Int NOT NULL")]
		public int emp_no
		{
			get
			{
				return this._emp_no;
			}
			set
			{
				if ((this._emp_no != value))
				{
					this._emp_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetryAttempts", DbType="Int")]
		public System.Nullable<int> RetryAttempts
		{
			get
			{
				return this._RetryAttempts;
			}
			set
			{
				if ((this._RetryAttempts != value))
				{
					this._RetryAttempts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActivated", DbType="Bit")]
		public System.Nullable<bool> IsActivated
		{
			get
			{
				return this._IsActivated;
			}
			set
			{
				if ((this._IsActivated != value))
				{
					this._IsActivated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit")]
		public System.Nullable<bool> IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this._IsLocked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeactivatedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeactivatedDateTime
		{
			get
			{
				return this._DeactivatedDateTime;
			}
			set
			{
				if ((this._DeactivatedDateTime != value))
				{
					this._DeactivatedDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LockedDateTime
		{
			get
			{
				return this._LockedDateTime;
			}
			set
			{
				if ((this._LockedDateTime != value))
				{
					this._LockedDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this._LastLogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
	}
	
	public partial class PinAuthProcedureResult
	{
		
		private int _emp_no;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Email;
		
		private System.Nullable<int> _RetryAttempts;
		
		private System.Nullable<bool> _IsActivated;
		
		private System.Nullable<bool> _IsLocked;
		
		private System.Nullable<System.DateTime> _DeactivatedDateTime;
		
		private System.Nullable<System.DateTime> _LockedDateTime;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _LastLogin;
		
		private int _RoleID;
		
		private string _SecretQuestion;
		
		private string _SecretAnswer;
		
		private System.Nullable<int> _emp_pin;
		
		private string _FirstName;
		
		private string _LastName;
		
		public PinAuthProcedureResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_no", DbType="Int NOT NULL")]
		public int emp_no
		{
			get
			{
				return this._emp_no;
			}
			set
			{
				if ((this._emp_no != value))
				{
					this._emp_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RetryAttempts", DbType="Int")]
		public System.Nullable<int> RetryAttempts
		{
			get
			{
				return this._RetryAttempts;
			}
			set
			{
				if ((this._RetryAttempts != value))
				{
					this._RetryAttempts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActivated", DbType="Bit")]
		public System.Nullable<bool> IsActivated
		{
			get
			{
				return this._IsActivated;
			}
			set
			{
				if ((this._IsActivated != value))
				{
					this._IsActivated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLocked", DbType="Bit")]
		public System.Nullable<bool> IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this._IsLocked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeactivatedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeactivatedDateTime
		{
			get
			{
				return this._DeactivatedDateTime;
			}
			set
			{
				if ((this._DeactivatedDateTime != value))
				{
					this._DeactivatedDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LockedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> LockedDateTime
		{
			get
			{
				return this._LockedDateTime;
			}
			set
			{
				if ((this._LockedDateTime != value))
				{
					this._LockedDateTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogin", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLogin
		{
			get
			{
				return this._LastLogin;
			}
			set
			{
				if ((this._LastLogin != value))
				{
					this._LastLogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecretQuestion", DbType="VarChar(50)")]
		public string SecretQuestion
		{
			get
			{
				return this._SecretQuestion;
			}
			set
			{
				if ((this._SecretQuestion != value))
				{
					this._SecretQuestion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecretAnswer", DbType="NChar(10)")]
		public string SecretAnswer
		{
			get
			{
				return this._SecretAnswer;
			}
			set
			{
				if ((this._SecretAnswer != value))
				{
					this._SecretAnswer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_pin", DbType="Int")]
		public System.Nullable<int> emp_pin
		{
			get
			{
				return this._emp_pin;
			}
			set
			{
				if ((this._emp_pin != value))
				{
					this._emp_pin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
	}
	
	public partial class spFastLoginResult
	{
		
		private string _emp_pin;
		
		public spFastLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_pin", DbType="VarChar(50)")]
		public string emp_pin
		{
			get
			{
				return this._emp_pin;
			}
			set
			{
				if ((this._emp_pin != value))
				{
					this._emp_pin = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
